# WD Workshop

https://github.com/sgulyano/wd_workshop

* topic 1
* topic 2

1. paragraph 1
2. paragraph 2

![cat](https://gossipstar.com/app/uploads/2019/09/S__64954371.jpg)

Write an instruction here.

In [6]:
a=10
print(a)

10


Create variables...

In [5]:
b = 4.2
print(b)

4.2


In [5]:
import numpy as np

In [4]:
import pandas

Numpy Array Creation

In [14]:
a = np.array([1,2,3])

In [8]:
print(a)

[1 2 3]


In [9]:
a

array([1, 2, 3])

In [10]:
'abc'

'abc'

In [11]:
print('abc')

abc


In [15]:
b = np.array([[1,2,3],
              [4,5,6]])

In [16]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
type(b)

numpy.ndarray

In [18]:
b.dtype

dtype('int64')

In [19]:
c = np.array([[1,'abc',3],
              [4,5,6]])

In [22]:
d = np.array([[1,2.1,3],
              [4,5,6]])

In [27]:
d

array([[1. , 2.1, 3. ],
       [4. , 5. , 6. ]])

In [28]:
print(d)

[[1.  2.1 3. ]
 [4.  5.  6. ]]


In [24]:
d.dtype

dtype('float64')

In [25]:
e = np.zeros((3,5))
print(e)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
f = np.ones((3,5))
print(f)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
np.arange(12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
np.arange(12).shape

(12,)

In [40]:
np.arange(12).reshape((3,4)).shape

(3, 4)

In [46]:
np.arange(24).reshape((3,4,2)).shape

(3, 4, 2)

In [47]:
h = np.arange(24).reshape((3,4,2))

In [48]:
h

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [51]:
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [60]:
h[1:,:2].flatten()

array([ 8,  9, 10, 11, 16, 17, 18, 19])

In [63]:
c = np.array([7,8,9])

In [62]:
a

array([1, 2, 3])

In [67]:
d

array([[1. , 2.1, 3. ],
       [4. , 5. , 6. ]])

In [71]:
e = np.arange(6).reshape((2,3))
e

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
d*e

array([[ 0. ,  2.1,  6. ],
       [12. , 20. , 30. ]])

In [79]:
np.log(e)

<ipython-input-79-c27605f42df2>:1: RuntimeWarning: divide by zero encountered in log
  np.log(e)


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791]])

In [81]:
np.sin(e)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427]])

Broadcasting

In [83]:
f = np.ones((3,5))
f

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [85]:
g = np.array([5,6,7,8,9])
g

array([5, 6, 7, 8, 9])

In [86]:
f*g

array([[5., 6., 7., 8., 9.],
       [5., 6., 7., 8., 9.],
       [5., 6., 7., 8., 9.]])

In [88]:
k = np.array([2.2, 5.4, 4.8])
k

array([2.2, 5.4, 4.8])

In [90]:
f*k[:,np.newaxis]

array([[2.2, 2.2, 2.2, 2.2, 2.2],
       [5.4, 5.4, 5.4, 5.4, 5.4],
       [4.8, 4.8, 4.8, 4.8, 4.8]])

In [91]:
k[:,np.newaxis].shape

(3, 1)

In [93]:
f.shape

(3, 5)

In [95]:
x = np.arange(24).reshape((3,4,2))
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [98]:
x*k[:,np.newaxis,np.newaxis]

array([[[  0. ,   2.2],
        [  4.4,   6.6],
        [  8.8,  11. ],
        [ 13.2,  15.4]],

       [[ 43.2,  48.6],
        [ 54. ,  59.4],
        [ 64.8,  70.2],
        [ 75.6,  81. ]],

       [[ 76.8,  81.6],
        [ 86.4,  91.2],
        [ 96. , 100.8],
        [105.6, 110.4]]])

In [101]:
a

array([1, 2, 3])

In [102]:
k

array([2.2, 5.4, 4.8])

In [105]:
a / k[:,np.newaxis]

array([[0.45454545, 0.90909091, 1.36363636],
       [0.18518519, 0.37037037, 0.55555556],
       [0.20833333, 0.41666667, 0.625     ]])

In [108]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [110]:
b = a
b

array([1, 2, 3])

In [111]:
b[1] = 100

In [112]:
b

array([  1, 100,   3])

In [113]:
a

array([  1, 100,   3])

In [114]:
a[2] = 300
a

array([  1, 100, 300])

In [115]:
b

array([  1, 100, 300])

In [116]:
c = a.copy()

In [117]:
c

array([  1, 100, 300])

In [118]:
a

array([  1, 100, 300])

In [119]:
c[1] = -10

In [120]:
c

array([  1, -10, 300])

In [121]:
a

array([  1, 100, 300])